module.exports = {
  printWidth: 100,
  semi: false,
  singleQuote: true,
  arrowParens: 'avoid',
  trailingComma: 'es5',
  experimentalTernaries: false,
  // plugins: ['@ianvs/prettier-plugin-sort-imports'],
  // importOrder: [
  //   '<BUILTIN_MODULES>',
  //   '',
  //   '^react$',
  //   '',
  //   '^vue$',
  //   '',
  //   '<THIRD_PARTY_MODULES>',
  //   '',
  //   '^#/(.*)$',
  //   '',
  //   '<TYPES>',
  //   '^[./]',
  // ],
  // importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  // importOrderTypeScriptVersion: '5.0.0',
}
